# 워드 임베딩

In [ ]:
# 학습할 텍스트 읽기 
import os.path

embedding_dim = 50                                       # 임베딩 차원수 설정

with open('C:/Users/LeeKyoungJun/Desktop/데이터캠퍼스/pytest/wiki_test.txt', 'r', encoding='utf-8') as f:  # 테스트용 파일 읽기 
    data = f.read()

In [2]:
# 문장단위 분리 및 형태소 분석기 기동
import rhinoMorph
from nltk.tokenize import sent_tokenize
import nltk
nltk.download('punkt')

sent_data = sent_tokenize(data)                       # 문장 단위 분리
rn = rhinoMorph.startRhino()                          # RHINO 기동

# print('type:', type(sent_data))
# print('length:', len(sent_data))           # 전체 문장의 개수
# print('sentence sample:', sent_data[:20])  # 형태소 분석 전 모습

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\LeeKyoungJun\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


filepath:  C:\Anaconda3\lib\site-packages
classpath:  C:\Anaconda3\lib\site-packages\rhinoMorph/lib/rhino.jar
RHINO started!


In [3]:
# # 텍스트의 형태소 분석
# total_lines = len(sent_data)
# cnt = 0
# with open('C:/Users/LeeKyoungJun/Desktop/데이터캠퍼스/pytest/word2vec/wiki202003_nationalcorpus_naverratings_morphed.txt', 'w', encoding='utf-8') as f:
#     for data_each in sent_data:
#         morphed_data_each = rhinoMorph.onlyMorph_list(rn, data_each, pos=['NNG', 'NNP', 'NP', 'VV', 'VA', 'XR', 'IC', 'MM', 'MAG', 'MAJ'])
#         joined_data_each = ' '.join(morphed_data_each)
#         if joined_data_each:
#             f.write(joined_data_each + '\n')
#         cnt += 1
#         if (cnt % 1000) == 0:  # 진행정도 확인을 위해 1000번째 문장마다 확인
#             print(round(cnt/total_lines * 100, 3), '%')
#     print('Morphological Analysis Completed.')

In [4]:
# # 형태소 분석 결과를 읽어 리스트로 만들기
# def read_data(filename, encoding='utf-8'):                # 읽기 함수 정의
#     with open(filename, 'r', encoding=encoding) as f:
#         data = [line.split(' ') for line in f.read().splitlines()]
#     return data


# data = read_data('C:/Users/LeeKyoungJun/Desktop/데이터캠퍼스/pytest/word2vec/wiki202003_nationalcorpus_naverratings_morphed.txt', 'utf-8')

# print(len(data))
# print(type(data))
# print(data[:3])

In [5]:
# # 임베딩 구성 
# from gensim.models import Word2Vec

# model = Word2Vec(sentences=data, size=embedding_dim, window=10, min_count=5, workers=4, sg=1)
# model.save('C:\Users\LeeKyoungJun\Desktop\데이터캠퍼스\pytest\word2vec\embedding_window10_mincnt5_skipgram.model')

# print('Completed.')

In [6]:
# # 임베딩 값 저장 
# words = list(model.wv.vocab)
# with open('C:/Users/LeeKyoungJun/Desktop/데이터캠퍼스/pytest/word2vec/embedding_window10_mincnt5_skipgram.txt', 'w') as f:
#     for word in words:
#         data = model.wv[word].tolist()      # 현재 단어의 임베딩 값을 가져온다
#         print('data_pre:', data)            # 현재 단어의 임베딩 값을 출력해본다

#         data.insert(0, word)                # 시작 부분에 해당 단어를 넣는다
#         print('data_after:', data)          # 현재 단어의 이름과 함께 임베딩 값을 출력해본다 

#         for item in data:                   # 단어 이름부터 시작하여 각 벡터의 값을 저장한다
#             f.write("%s " % item)
#         f.write("\n")

In [7]:
# 유사어 찾기
from gensim.models import Word2Vec
model = Word2Vec.load('C:/Users/LeeKyoungJun/Desktop/데이터캠퍼스/pytest/word2vec/embedding_window10_mincnt5_skipgram.model')    # 미리 만들어진 워드 임베딩을 사용한다 

print('--- 유사단어 출력 ---')
similarWords = model.wv.most_similar(positive=['행복', '웃음', '밝', '기쁨'], topn=5)
print(similarWords)

word = []
for similarWord in similarWords:
    word.append(similarWord[0])

print(word)

--- 유사단어 출력 ---
[('흐뭇', 0.8909333944320679), ('마음', 0.8865163922309875), ('기쁘', 0.8699381947517395), ('마음속', 0.8504815101623535), ('즐겁', 0.8447961807250977)]
['흐뭇', '마음', '기쁘', '마음속', '즐겁']


In [8]:
# 두 단어 사이의 유사도 계산
print('--- 두 단어의 유사도 계산 ---')
print('한국과 일본:', model.wv.similarity('한국', '일본'))
print('한국과 미국:', model.wv.similarity('한국', '미국'))
print('한국과 중국:', model.wv.similarity('한국', '중국'))

--- 두 단어의 유사도 계산 ---
한국과 일본: 0.85150576
한국과 미국: 0.7342306
한국과 중국: 0.6941229


# 한글 네이버 다중분류

In [10]:
# Data Loading Preparation
import os

train_dir = 'C:/Users/LeeKyoungJun/Desktop/데이터캠퍼스/pytest/네이버뉴스-생활문화_다중/train'
test_dir = 'C:/Users/LeeKyoungJun/Desktop/데이터캠퍼스/pytest/네이버뉴스-생활문화_다중/test'

label_types = ['건강정보', '공연전시', '도로교통', '여행레저', '음식맛집', '자동차시승기', '종교', '책', '패션뷰티']

In [11]:
# text와 labels 리스트를 만드는 함수를 작성한다
def make_texts_labels(dir, label_types, encode='utf8'):    	# texts와 labels 리스트를 만드는 함수
  texts = []
  labels = []
  
  for label_type in label_types:
    dir_name = os.path.join(dir, label_type) 		  # 각각의 label 폴더에 접근한다
    for fname in os.listdir(dir_name):
      if fname[-4:] == '.txt':                    # 마지막 4 글자가 .txt 로 끝나는지를 확인한다
        f = open(os.path.join(dir_name, fname), encoding=encode)
        texts.append(f.read())                    # 텍스트를 읽어서 texts 리스트에 연결한다
        f.close()
        
        if label_type == label_types[0]:          # 만약 현재 폴더가 '건강정보' 폴더라면
          labels.append(0)                        # texts와 같은 순서의 labels 리스트에는 0을 저장한다
        elif label_type == label_types[1]:
          labels.append(1)
        elif label_type == label_types[2]:
          labels.append(2)
        elif label_type == label_types[3]:
          labels.append(3)
        elif label_type == label_types[4]:
          labels.append(4)
        elif label_type == label_types[5]:
          labels.append(5)
        elif label_type == label_types[6]:
          labels.append(6)
        elif label_type == label_types[7]:
          labels.append(7)
        elif label_type == label_types[8]:
          labels.append(8)
          
  return texts, labels

In [12]:
# Train Data Loading
# 훈련 데이터의 텍스트와 라벨을 받아온다

texts, labels = make_texts_labels(train_dir, label_types)

print('texts 0:', texts[0])
print('texts len:', len(texts))
print('labels 0:', labels[0])
print('labels len:', len(labels))

texts 0: SK케미칼, 백신 사업 분사 결정 : 네이버 뉴스







글로벌화 단계 진입…올해 백신사업 분사로 별도법인 설립SK케미칼이 주력 사업부문인 백신 사업을 별도 법인으로 분리한다.SK케미칼은 글로벌 프리미엄 백신 회사로 도약을 위해 올해 안에 백신 사업을 분사할 예정이라고 12일 공시했다.SK케미칼은 2006년부터 백신을 미래 성장 동력으로 육성하기 위해 인프라구축에 약 4000억원을 투자했다. 지난 2012년에는 경북 안동에 세포배양 백신 등 차세대 백신을 생산할 수 있는 백신공장 'L하우스'를 짓고 독감백신, 대상포진백신 등을 생산했다. SK케미칼의 사업 부문별 비중을 보면 합성의약품은 약 60%, 백신은 40% 규모다.SK케미칼은 앞으로 분사한 별도법인에 대한 SI(전략적투자자)를 본격적으로 유치하고 기업공개(IPO)를 통해 주주가치 제고에 기여하겠다는 계획이다.SK케미칼 측은 "지속적인 노력의 성과로 사노피 파스퇴르와 차세대폐렴구균 공동개발 계약 체결, 세포배양방식의 독감백신 3·4가 및 대상포진 백신 출시 등 다양한 성과를 창출해 왔다"며 "자체 기술 경쟁력을 바탕으로 글로벌화의 본격화 단계에 진입했다"고 밝혔다.김지섭기자 cloud50@dt.co.kr 디지털타임스 홈페이지 바로가기 / SNS 바로가기디지털타임스 영문뉴스 바로가기 / 카드뉴스 바로가기김지섭
	

texts len: 90
labels 0: 0
labels len: 90


In [13]:
# Analyzing Morphology
# 한글은 tokenizing을 위해서 먼저 형태소분석을 해야 한다
import rhinoMorph
rn = rhinoMorph.startRhino()                         		

# 리스트 컴프리헨션으로 실질형태소만을 리스트로 가져온다
texts = [rhinoMorph.onlyMorph_list(rn, sentence, pos=['NNG', 'NNP', 'NP', 'VV', 'VA', 'XR', 'IC', 'MM', 'MAG', 'MAJ'], eomi=False) for sentence in texts]

print(texts)
print(texts[0])

filepath:  C:\Anaconda3\lib\site-packages
classpath:  C:\Anaconda3\lib\site-packages\rhinoMorph/lib/rhino.jar
JVM is already started~
RHINO started!
[['SK', '케미칼', '백신', '사업', '분사', '결정', '네이버', '뉴스', '글로벌', '단계', '진입', '올해', '백신', '사업', '분사', '별도', '법인', '설립', 'SK', '케미칼', '주력', '사업', '부문', '백신', '사업', '별도', '법인', '분리', 'SK', '케미칼', '글로벌', '프리미엄', '백신', '회사', '도약', '위하', '올해', '안', '백신', '사업', '분사', '예정', '공시', 'SK', '케미칼', '백신', '미래', '성장', '동력', '육성', '위하', '인프라', '구축', '약', '투자', '지나', '경북', '안동', '세포', '배양', '백신', '차세대', '백신', '생산', '백신', '공장', '하우스', '짓', '독감', '백신', '대상포진', '백신', '등', '생산', 'SK', '케미칼', '사업', '부문', '비중', '합성', '의약품', '약', '백신', '규모', 'SK', '케미칼', '앞', '분사', '하', '별도', '법인', '대하', '전략적', '투자자', '본격적', '유치', '기업공개', '통하', '주주', '가치', '제고', '기여', '계획', 'SK', '케미칼', '지속적', '노력', '성과', '사노', '피', '파스퇴르', '차세대', '폐렴', '구균', '공동', '개발', '계약', '체결', '세포', '배양', '방식', '독감', '백신', '가', '및', '대상포진', '백신', '출시', '다양', '하', '성과', '창출', '자체', '기술', '경쟁력', '바탕', '글로벌', '본격화', 

In [15]:
# Data Tokenizing
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
import math

validation_ratio = math.floor(len(texts) * 0.3)    	# 30%는 검증데이터로 사용한다. 나머지는 훈련데이터
max_words = 10000                                   # 데이터셋에서 가장 빈도 높은 10,000 개의 단어만 사용한다
maxlen = 200                                        # 200개 이후의 단어는 버린다
class_number = 9                                    # 분류할 클래스의 수

tokenizer = Tokenizer(num_words=max_words)  	      # 상위빈도 10,000 개의 단어만을 추려내는 Tokenizer 객체 생성
tokenizer.fit_on_texts(texts)                       # 단어 인덱스를 구축한다
word_index = tokenizer.word_index               	  # 단어 인덱스만 가져온다

C:\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is 

In [16]:
# 전체 데이터가 가지고 있는 토큰의 수를 보여준다. texts_to_sequences()를 거쳐야 10,000개만 남는다. 

print('전체에서 %s개의 고유한 토큰을 찾았습니다.' % len(word_index))
print('word_index type: ', type(word_index))
print('word_index: ', word_index)

전체에서 5351개의 고유한 토큰을 찾았습니다.
word_index type:  <class 'dict'>
word_index:  {'하': 1, '되': 2, '있': 3, '뉴스': 4, '네이버': 5, '및': 6, '이': 7, '기자': 8, '그': 9, '위하': 10, '한국': 11, '시간': 12, '서울': 13, '보': 14, '가': 15, '받': 16, '배포': 17, '대하': 18, '제공': 19, '무단': 20, '전재': 21, '김': 22, '주': 23, '금지': 24, '고객': 25, '통하': 26, '올림픽': 27, '평창': 28, '설': 29, '바로': 30, '제품': 31, '작품': 32, '제보': 33, '없': 34, '스포츠서울': 35, '발생': 36, '작가': 37, '밝히': 38, '다양': 39, '서비스': 40, '사진': 41, '자궁': 42, '이상': 43, '가장': 44, '사람': 45, '시장': 46, '계획': 47, '대표': 48, '때': 49, '말하': 50, '정부': 51, '책': 52, '진행': 53, '관련': 54, '사업': 55, '따르': 56, '한경': 57, '컬러': 58, '약': 59, '경우': 60, '이번': 61, '수': 62, '지역': 63, '오': 64, '위': 65, '교수': 66, '해외': 67, '공식': 68, '크': 69, '나': 70, '연휴': 71, '가격': 72, '속': 73, '지난해': 74, '공연': 75, '등': 76, '한': 77, '함께': 78, '지원': 79, '핑크': 80, '채널': 81, '김지현': 82, '도로': 83, '차량': 84, '안전': 85, '문제': 86, '국가': 87, '시': 88, '사량': 89, '많': 90, '기간': 91, '만들': 92, '녹': 93, '연구': 94, '결과': 95, '여성'

In [17]:
# Data Sequencing
# train 데이터를 Sequencing 한다
# 상위 빈도 10,000개의 단어를 word_index의 숫자 리스트로 변환. Tokenizer 결과가 여기서 반영된다
data = tokenizer.texts_to_sequences(texts) 

# maxlen의 수만큼으로 2D 텐서를 만든다
data = pad_sequences(data, maxlen=maxlen)

print('data:', data)

data: [[   0    0    0 ...   15   22 1094]
 [ 872 1096  144 ...   33  516   35]
 [   0    0    0 ...   15   22 1094]
 ...
 [  62    3 5264 ...    6   17   24]
 [   0    0    0 ...  197 1563  176]
 [   0    0    0 ...    6   17   24]]


In [18]:
# One-Hot Encoding
# 원-핫 인코딩 함수
def to_one_hot(labels, dimension):
      results = np.zeros((len(labels), dimension))
      for i, label in enumerate(labels):
         results[i, label] = 1.
      return results

# 입력층에는 원-핫 인코딩을 수행하지 않는다
# data = to_one_hot(data, dimension=max_words)

# 출력층만 원-핫 인코딩을 수행한다 
labels = to_one_hot(labels, dimension=class_number)

In [19]:
# Train data와 Validation data 준비

print('데이터 텐서의 크기:', data.shape)        	# (90, 10000)
print('레이블 텐서의 크기:', labels.shape)      	# (90, 9) data와 label이 모두 2D 텐서가 되었음

indices = np.arange(data.shape[0])      		      # 0 ~ 89 까지의 숫자를 생성
np.random.shuffle(indices)                        # 0 ~ 89 까지의 숫자를 랜덤하게 섞음
data = data[indices]                              # 이것을 인덱스로 하여 2D 텐서 데이터를 섞음
labels = labels[indices]                          # label도 같은 순서로 섞음

x_train = data[validation_ratio:]                 # 훈련데이터의 70%를 훈련데이터
y_train = labels[validation_ratio:]               # 훈련데이터의 70%를 훈련데이터 Label
x_val = data[:validation_ratio]                   # 훈련데이터의 30%를 검증데이터
y_val = labels[:validation_ratio]                 # 훈련데이터의 30%를 검증데이터 Label

데이터 텐서의 크기: (90, 200)
레이블 텐서의 크기: (90, 9)


In [20]:
# 출력층의 형태
print(labels)

[[0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0.

In [21]:
# Train data와 Validation data 준비

print('데이터 텐서의 크기:', data.shape)        	# (90, 10000)
print('레이블 텐서의 크기:', labels.shape)      	# (90, 9) data와 label이 모두 2D 텐서가 되었음

indices = np.arange(data.shape[0])      		      # 0 ~ 89 까지의 숫자를 생성
np.random.shuffle(indices)                        # 0 ~ 89 까지의 숫자를 랜덤하게 섞음
data = data[indices]                              # 이것을 인덱스로 하여 2D 텐서 데이터를 섞음
labels = labels[indices]                          # label도 같은 순서로 섞음

x_train = data[validation_ratio:]                 # 훈련데이터의 70%를 훈련데이터
y_train = labels[validation_ratio:]               # 훈련데이터의 70%를 훈련데이터 Label
x_val = data[:validation_ratio]                   # 훈련데이터의 30%를 검증데이터
y_val = labels[:validation_ratio]                 # 훈련데이터의 30%를 검증데이터 Label

데이터 텐서의 크기: (90, 200)
레이블 텐서의 크기: (90, 9)


In [23]:
# 모델 정의하기 - Word2Vec Embedding (1), 임베딩 딕셔너리 로딩
embeddings_index = {}
f = open('C:/Users/LeeKyoungJun/Desktop/데이터캠퍼스/pytest/word2vec/embedding_window10_mincnt5_skipgram.txt', encoding='CP949')   #_big : CP949
for line in f:
    values = line.split()
    word = values[0]                                  # 각 행의 단어
    coefs = np.asarray(values[1:], dtype='float32')   # 각 단어의 임베딩값
    embeddings_index[word] = coefs
f.close()

print('%s개의 단어 벡터를 찾았습니다.' % len(embeddings_index))

143775개의 단어 벡터를 찾았습니다.


In [24]:
# 모델 정의하기 - Word2Vec Embedding (2), 임베딩 행렬 구성
embedding_matrix = np.zeros((max_words, embedding_dim))     # 0으로 채워진 빈 행렬 구성
for word, i in word_index.items():
    if i < max_words:                                       # max_words 이하의 범위에서 순회
        embedding_vector = embeddings_index.get(word)       # 해당 단어의 임베딩 벡터를 가져온다 
        if embedding_vector is not None:
            embedding_matrix[i] = embedding_vector          # 임베딩 값을 해당 행렬 위치에 주입한다

In [25]:
# 모델 정의하기 - Word2Vec Embedding (3), 임베딩 층 쌓기
from tensorflow.keras import models
from tensorflow.keras import layers

model = models.Sequential()                 		# 모델을 새로 정의

# 임베딩 층. 나중에 임베딩된 입력을 Flatten 층에서 펼치기 위해 input_length(=maxlen)를 지정. 출력층은 (input_dim, input_length, output_dim)가 됨
model.add(layers.Embedding(input_dim=max_words, output_dim=embedding_dim, input_length=maxlen))
model.add(layers.Flatten())                     # 3D 임베딩 텐서를 (input_dim, input_length * output_dim) 크기의 2D 텐서로 펼친다

# 은닉층
model.add(layers.Dense(units=32, activation='relu'))

# 출력층. 출력 노드는 분류 개수인 9. 활성화 함수는 sigmoid와 성격이 같으나 다중분류에 사용되는 함수인 softmax 함수를 사용한다. 확률값을 출력
model.add(layers.Dense(units=class_number, activation='softmax'))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [26]:
# 모델 정의하기 - Word2Vec Embedding (4), 임베딩 행렬의 값 주입
model.layers[0].set_weights([embedding_matrix])
model.layers[0].trainable = False

In [27]:
# 모델 정의하기, Keras Embedding
# 보다 쉽게 사용할 수 있는 Keras Embedding으로 진행
from tensorflow.keras import models
from tensorflow.keras import layers

embedding_dim = 50                              # 임베딩의 차원을 설정한다. 보통 200까지에서 적절히 설정한다. 
model = models.Sequential()                 		# 모델을 새로 정의

# 임베딩 층. 나중에 임베딩된 입력을 Flatten 층에서 펼치기 위해 input_length(=maxlen)를 지정. 출력층은 (input_dim, input_length, output_dim)가 됨
model.add(layers.Embedding(input_dim=max_words, output_dim=embedding_dim, input_length=maxlen))
model.add(layers.Flatten())                     # 3D 임베딩 텐서를 (input_dim, input_length * output_dim) 크기의 2D 텐서로 펼친다

# 은닉층
model.add(layers.Dense(units=32, activation='relu'))

# 출력층. 출력 노드는 분류 개수인 9. 활성화 함수는 sigmoid와 성격이 같으나 다중분류에 사용되는 함수인 softmax 함수를 사용한다. 확률값을 출력
model.add(layers.Dense(units=class_number, activation='softmax'))

In [28]:
# 모델 요약 출력
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 200, 50)           500000    
_________________________________________________________________
flatten_1 (Flatten)          (None, 10000)             0         
_________________________________________________________________
dense_2 (Dense)              (None, 32)                320032    
_________________________________________________________________
dense_3 (Dense)              (None, 9)                 297       
Total params: 820,329
Trainable params: 820,329
Non-trainable params: 0
_________________________________________________________________
