# Chap 6. 디렉토리와 파일 관리하기
## 1. OS 모듈을 통한 디렉토리 관리
### rmdir(), removedirs() <- 쓰는 일은 별로 없을 것임. 실수로 삭제하면 복구하기 힘들기 때문에.

### 파일 경로 입력시에는 \를 두 번이 아닌 한 번만 써야 함

In [124]:
import os

print("현재 디렉토리 : %s" % os.getcwd() )
os.chdir("C:\\py_temp")
print("현재 디렉토리 : %s" % os.getcwd() )

현재 디렉토리 : C:\temp
현재 디렉토리 : C:\py_temp


## 현재 디렉토리 확인 : .getcwd() <= CurrentWorkingDirectory
## 디렉토리 변경 : .chdir("절대경로 또는 상대경로") <= CHangeDIRectory

In [126]:
os.listdir(".")

['.ipynb_checkpoints',
 'RHINO.ipynb',
 'sampleFile',
 '파이썬 연습 1.ipynb',
 '파이썬 연습2(0708 수).ipynb']

In [127]:
for i in os.listdir(".") :
    print(i)

.ipynb_checkpoints
RHINO.ipynb
sampleFile
파이썬 연습 1.ipynb
파이썬 연습2(0708 수).ipynb


## 경로의 폴더와 파일 목록 출력 : .listdir("경로")
## 위의 for문처럼도 출력가능

In [129]:
print( os.path.exists(".\\파이썬 연습 1.ipynb"))

True


## 경로에 폴더나 파일 존재하는지 확인 : os.path.exists("경로")
### 결과값은 Boolean으로

In [135]:
os.mkdir(".\\makedir테스트2")
os.makedirs(".\\makedirs테스트\\makedirs테스트2")
os.listdir(".")

['.ipynb_checkpoints',
 'makedirs테스트',
 'makedir테스트',
 'makedir테스트1',
 'makedir테스트2',
 'RHINO.ipynb',
 'sampleFile',
 '파이썬 연습 1.ipynb',
 '파이썬 연습2(0708 수).ipynb']

## 폴더 생성 : os.mkdir("경로"), os.makedirs("경로")
### mkdir은 단일 폴더, makedirs는 하위폴더까지 여러 개 생성
### mk와 make 헷갈릴 듯
### 두 명령어 모두 이미 폴더가 존재하면 FileExistsError 뜸

In [139]:
# os.rmdir(".\\makedirs테스트")
os.removedirs(".\\makedir테스트1")
os.listdir(".")

['.ipynb_checkpoints',
 'makedir테스트',
 'makedir테스트2',
 'RHINO.ipynb',
 'sampleFile',
 '파이썬 연습 1.ipynb',
 '파이썬 연습2(0708 수).ipynb']

## 폴더 삭제 : rmdir(), removedirs()
### 두 명령어 모두 삭제할 폴더 내에 뭐가 들어가 있으면 실행 안됨
### 단, removedirs의 경우 삭제할 폴더의 하위에 폴더만 있다면 다같이 삭제됨

In [143]:
print(os.getcwd())

file = open("test.txt", "w")
file.write("테스트")
file.close()

C:\py_temp


## 텍스트 파일 열어서(생성해서) 쓰고 저장하기
### var = open( "(경로+)파일명" , "w") <= w가 아닌 "w"
### var.write("입력할 내용") 
### var.close()
### "w" 쓰면 기존 내용 삭제 후 "덮어쓰기"가 되므로 우리는 덧붙이는 "a" 모드를 많이 쓸 것임

In [145]:
file = open(".\\sampleFile\\readme.txt", "r")
file.readlines()

['1.새우깡\n', '2.맛동산\n', '3.감자깡\n', '4.고구마깡\n', '5.꼬깔콘']

In [155]:
file = open(".\\sampleFile\\readme.txt", "r")
txtFile = file.readlines()
print(txtFile[0])
print(txtFile[4] + "\n")
print("=" *80)

for i in txtFile :
    print(i)

1.새우깡

5.꼬깔콘

1.새우깡

2.맛동산

3.감자깡

4.고구마깡

5.꼬깔콘


## .readlines()를 변수에 저장해서 라인별로 출력할 수도 있고, for문으로도 쓸 수 있다.

In [39]:
import pandas as pd

no = []
subject_name = []

no.append(1)
no.append(2)
no.append(3)

subject_name.append('수학')
subject_name.append('과학')
subject_name.append('빅데이터')

subject = pd.DataFrame()
subject['과목번호'] = no
subject['과목명'] = subject_name

# subject.to_csv(".\\subject.csv", encoding = "utf-8-sig", index=False)
subject.to_excel(".\\subject.xlsx", index=False)

## Dataframe만들고 각 컬럼에 리스트 넣고 변수.to_csv("") 로 csv 파일 저장, 변수.to_excel로 xlsx(xls는 이 방식으로는 안됨!) 파일 저장

# 디렉토리와 파일 관리하기 연습문제

In [22]:
# 1

import os

print("생성할 폴더명을 입력하세요(현재 폴더 : %s)" % os.getcwd() )
foldName = input("")

if os.path.exists(foldName) == False : 
    os.mkdir(".\\" + foldName)
    print("%s 폴더를 생성했습니다. (경로 : %s\\%s)" %(foldName, os.getcwd(), foldName))
else :
    makedFolder = foldName + "_2"
    os.mkdir(makedFolder)
    print("%s 폴더가 이미 존재하므로 %s 폴더를 생성했습니다. (경로 : %s\\%s)" %(foldName, makedFolder, os.getcwd(), makedFolder))
    

생성할 폴더명을 입력하세요(현재 폴더 : C:\py_temp)
k_2
k_2 폴더가 이미 존재하므로 k_2_2 폴더를 생성했습니다. (경로 : C:\py_temp\k_2_2)


In [61]:
# 2

navCount = tCount = blogCount = 0

p2File = open(".\\sampleFile\\url.txt", "r")
sen = p2File.readlines()

count = 0
for i in range(1, len(sen)+1) :
    core = sen[count].split('/')
    if core[2] == "blog.naver.com" :
        navCount += 1
    elif core[2] == "blog.tistory.com" :
        tCount += 1
    elif core[2] == "blog.blog.me" :
        blogCount += 1
    count+=1

print("blog.naver.com 의 개수는 모두 %s개 입니다." % navCount)
print("blog.tistory.com 의 개수는 모두 %s개 입니다." % tCount)
print("blog.blog.com 의 개수는 모두 %s개 입니다." % blogCount)

blog.naver.com 의 개수는 모두 3개 입니다.
blog.tistory.com 의 개수는 모두 2개 입니다.
blog.blog.com 의 개수는 모두 2개 입니다.


In [93]:
# 3
import pandas as pd
# os.path.exists(".\\sampleFile\\댓글내용.xlsx")

p3Excel = pd.read_excel(".\\sampleFile\\댓글내용.xlsx")
for i in range(0, len(p3Excel)) :
    print(p3Excel['댓글내용'][i])

첫번째 댓글입니다
두번째 댓글입니다
세번째 댓글입니다
네번째 댓글입니다
다섯번째 댓글입니다


# 데이터 만질 때 원본은 항상 그대로 남겨두기

# Chap 7. 예외처리

In [98]:
try : 
    var = int(input("숫자입력해 : "))
except (ValueError, ZeroDivisionError) :
    print("숫자 입력해라고요")
else :
    print("잘했누")

숫자입력해 : 싫어
숫자 입력해라고요


## except에 오류 종류 여러 개 쓸 수 있음. ex) (ValueError, ZeroDivisionError)

In [106]:
try :
    print("값 두 개를 입력받아 나누기를 수행합니다.\n")
    int1 = int(input("첫 번째 숫자 입력 : "))
    int2 = int(input("두 번째 숫자 입력 : "))
    print("%s를 %s로 나눈 값은 %s입니다." %(int1, int2, (int1/int2)))
except ValueError : 
    print("숫자 입력 안했누")
except ZeroDivisionError :
    print("%s(으)로 %s(을)를 나눌 수 있을거라 생각해?" %(int2, int1))

값 두 개를 입력받아 나누기를 수행합니다.

첫 번째 숫자 입력 : 5
두 번째 숫자 입력 : 0
0(으)로 5(을)를 나눌 수 있을거라 생각해?


## except 여러 개 쓸 수 있음

In [107]:
try :
    int1 = int(input("숫자만 입력 : "))
except :
    print("숫자만 입력하라고;")

숫자만 입력 : 만
숫자만 입력하라고;


## 예외처리 연습문제

In [114]:
# 1
import os

try :
    txtFile = open(".\\sampleFile\\예외처리연습.txt", "r")
    lines = txtFile.readlines()
    countOfLine = int(input("몇 건을 출력할까요? : "))

    for i in range(0,countOfLine) :
        print(lines[i])
except IndexError :
    print("모든 행이 출력 완료되었습니다")

몇 건을 출력할까요? : 10
홍길동

일지매

전우치

강감찬

신사임당 

모든 행이 출력 완료되었습니다


# Chap 8. Numpy와 Pandas 모듈을 활용한 정형 데이터 관리
## 1. Numpy 모듈을 활용한 데이터 관리

In [1]:
import numpy as np

In [2]:
data1 = [1,2,3,4,5]
arr1 = np.array(data1)

In [3]:
arr1.shape

(5,)

In [4]:
arr1.dtype

dtype('int32')

## numpy 내장함수 .dtype 으로 배열 자료형 알 수 있음

In [5]:
arr4 = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## arr4 = np.array( [ [a,b], [c,d] ] ) 형태로 2차원 배열 가능

In [6]:
arr5 = np.array([ [1,2], [3,4] ])
arr6 = np.array([ [4,3], [2,1] ])
arr5 + arr6

array([[5, 5],
       [5, 5]])

In [7]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## numpy 내장함수 .arange(num) 으로 0부터 num까지 1차원 정수 배열 만들 수 있음. num에 음수는 안들어가짐

## 빈 배열 만드려면 arr1 = np.array([])  ()안에 [] 써야 함

In [8]:
arr1[3]
arr1[3:]
arr1[:] # 전체 요소

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr1 = np.random.rand(3,3)
arr1

array([[0.87846573, 0.66295247, 0.68157452],
       [0.95078595, 0.42052118, 0.40599642],
       [0.71358058, 0.54236058, 0.87342366]])

## numpy의 random 함수의 randn(n,m) 은 n행m열의 가우시간 정규분포 따르는 난수 생성
## numpy의 random 함수의 rand(n,m)은 n행m열의 0~1 사이 난수 생성
## 둘 다 대괄호 안쓰는 것 유의

In [10]:
arr2 = [ [-1,-2], [3,4] ]
np.abs(arr2)

array([[1, 2],
       [3, 4]])

In [11]:
np.square(arr2)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [12]:
arr3 = [ [1.5, 1.1], [2.0, 3.4] ]
np.ceil(arr3)

array([[2., 2.],
       [2., 4.]])

In [13]:
np.floor(arr3)

array([[1., 1.],
       [2., 3.]])

In [14]:
np.isnan(arr3)

array([[False, False],
       [False, False]])

In [15]:
np.isinf(arr3)

array([[False, False],
       [False, False]])

In [16]:
np.cos(arr3)

array([[ 0.0707372 ,  0.45359612],
       [-0.41614684, -0.96679819]])

In [17]:
# np.sort(arr3)
np.sort(arr3)[::-1]


array([[2. , 3.4],
       [1.1, 1.5]])

In [18]:
np.sort(arr3, axis = 0)

array([[1.5, 1.1],
       [2. , 3.4]])

## .sort에 axis=0 옵션 쓰면 행 방향으로 정렬가능(?)

## 내림차순 정렬 이상한데?

In [19]:
np.isinf(arr3)

array([[False, False],
       [False, False]])

In [20]:
arr1 = np.random.randn(5,3)
arr1

array([[-0.40298878, -0.59920273,  0.87431579],
       [-0.74575132,  1.25400705,  0.9819929 ],
       [ 0.96536701,  2.11543335, -0.91941838],
       [ 1.06089135,  0.64395426,  0.91561276],
       [ 2.42137624,  0.26381573, -0.63558296]])

In [21]:
# np.sum(arr1)
np.sum(arr1, axis = 1)

array([-0.12787572,  1.49024863,  2.16138198,  2.62045837,  2.04960902])

## .sum(배열) : 전체 요소 합 계산
### axis=1 옵션 쓰면 각 열 간의 합을 계산
### axis=0 옵션 쓰면 각 행 간의 합을 계산

In [22]:
np.mean(arr1)

0.5462548185791724

## .mean(배열) 전체 요소의 평균 계산
### 여기서도 axis 옵션 사용해서 각 열 또는 각 행 간의 평균 계산 가능

## 전체 성분의 표준편차, 분산, 최소값, 최대값 계산 (.std, .var, .min, .max)
### 여기서도 옵션으로 axis 가능

In [23]:
arr1

array([[-0.40298878, -0.59920273,  0.87431579],
       [-0.74575132,  1.25400705,  0.9819929 ],
       [ 0.96536701,  2.11543335, -0.91941838],
       [ 1.06089135,  0.64395426,  0.91561276],
       [ 2.42137624,  0.26381573, -0.63558296]])

In [26]:
np.argmax(arr1, axis=0)

array([4, 2, 1], dtype=int64)

## .argmin, .argmax : 배열의 최소, 최대값이 위치한 인덱스 출력
## Q. argmin, argmax의 axis 옵션 주었을 때 나오는 값 이해 못하겠음
### 인덱스는 왼->오, 위->아래 순서고 0부터 시작

In [28]:
arrEnd = np.arange(10)
arrEnd

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.cumsum(arrEnd)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

## .cumsum, .cumprod : 누적합, 누적곱 계산. 숫자형이 아닌 배열값으로 리턴

In [77]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

a[0:1,0:2]

array([[1, 2]])

## numpy 슬라이싱 할 때는 위처럼 [lowRange, colRange] 이래야됨. a[lowRange][colRange] 아님!
## 근데 하나의 요소값을 받을 때는 [][] 이렇게도 됨.

# numpy 연습문제

In [50]:
# 1
import numpy as np

p1_np = np.array([ [10, 20, 30], [40, 50, 60], [70, 80, 90], [100, 110, 120] ])
p1_np

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [82]:
# 2

p2_li = [p1_np[0,1], p1_np[1,2]]
p2_li

[20, 60]

In [78]:
# 3

p3_np = p1_np[0:2, 1:3]
p3_np

array([[20, 30],
       [50, 60]])

## pandas 연습문제

In [35]:
# 1

pd_p1 = {'번호' : ['1번', '2번', '3번'],
      '이름' : ['홍길동', '전우치', '강감찬'],
      '생일' : ['1975', '', '1982']
     }
pd_p1 = pd.DataFrame(pd_p1, columns = ['번호', '이름', '생일'])
pd_p1

번호   이름    생일
0  1번  홍길동  1975
1  2번  전우치      
2  3번  강감찬  1982

In [36]:
# 2

pd_p2 = pd.read_excel(".\\sampleFile\\부품구입대장.xlsx")
pd_p2.rename(columns = {'Unnamed: 0' : '날짜', 'Unnamed: 2' : '품목', 'Unnamed: 3' : '수량', 'Unnamed: 5' : '금액'},
                inplace = True)
pd_p2 = pd_p2[['날짜', '품목', '수량', '금액']]
pd_p2 = pd_p2.loc[3:]
pd_p2 = pd_p2.reset_index(drop=True)
pd_p2

날짜          품목  수량        금액
0   2019-08-23 00:00:00       ANGLE  21    672000
1   2019-09-09 00:00:00          백관  44   2464000
2   2019-06-18 00:00:00         절연판  40   1800000
3   2019-03-13 00:00:00  P/Z O-RING  11    418000
4   2019-05-11 00:00:00         알코올  38    304000
5   2019-06-28 00:00:00         실리콘  30   4500000
6   2019-02-16 00:00:00         소모품   4      8800
7   2019-10-22 00:00:00       MOTOR  14    420000
8   2019-03-18 00:00:00  PAPER BRSH  13    520000
9   2019-07-17 00:00:00        불화카리  23   1909000
10  2019-07-23 00:00:00         마크펜  33     99000
11  2019-03-20 00:00:00         NUT  20    300000
12  2019-01-27 00:00:00         윤활유  30  60000000
13  2019-07-11 00:00:00         소모품  50    110000
14  2019-05-16 00:00:00        BITE  14   1204000

In [37]:
# 3
pd_p3 = pd_p2.loc[ pd_p2['금액'] > 100000 ]
pd_p3 = pd_p3.sort_values( ['금액'], ascending = [False] )
pd_p3

날짜          품목  수량        금액
12  2019-01-27 00:00:00         윤활유  30  60000000
5   2019-06-28 00:00:00         실리콘  30   4500000
1   2019-09-09 00:00:00          백관  44   2464000
9   2019-07-17 00:00:00        불화카리  23   1909000
2   2019-06-18 00:00:00         절연판  40   1800000
14  2019-05-16 00:00:00        BITE  14   1204000
0   2019-08-23 00:00:00       ANGLE  21    672000
8   2019-03-18 00:00:00  PAPER BRSH  13    520000
7   2019-10-22 00:00:00       MOTOR  14    420000
3   2019-03-13 00:00:00  P/Z O-RING  11    418000
4   2019-05-11 00:00:00         알코올  38    304000
11  2019-03-20 00:00:00         NUT  20    300000
13  2019-07-11 00:00:00         소모품  50    110000

In [38]:
# 4
pd_p4 = pd_p3[ ['품목', '금액'] ]
pd_p4

품목        금액
12         윤활유  60000000
5          실리콘   4500000
1           백관   2464000
9         불화카리   1909000
2          절연판   1800000
14        BITE   1204000
0        ANGLE    672000
8   PAPER BRSH    520000
7        MOTOR    420000
3   P/Z O-RING    418000
4          알코올    304000
11         NUT    300000
13         소모품    110000

In [39]:
# 5

pd_p5 = pd.DataFrame( pd_p2, columns = ['날짜', '품목', '수량', '금액', '코드'] )
pd_p5['코드'] = ''

i = 0
while i < len(pd_p5) :
    if pd_p5['품목'][i] == '백관' :
        pd_p5['코드'][i] = 'A1'
    elif pd_p5['품목'][i] == '절연판' :
        pd_p5['코드'][i] = 'B1'
    elif pd_p5['품목'][i] == '실리콘' :
        pd_p5['코드'][i] = 'C1'
    i += 1

pd_p5

날짜          품목  수량        금액  코드
0   2019-08-23 00:00:00       ANGLE  21    672000    
1   2019-09-09 00:00:00          백관  44   2464000  A1
2   2019-06-18 00:00:00         절연판  40   1800000  B1
3   2019-03-13 00:00:00  P/Z O-RING  11    418000    
4   2019-05-11 00:00:00         알코올  38    304000    
5   2019-06-28 00:00:00         실리콘  30   4500000  C1
6   2019-02-16 00:00:00         소모품   4      8800    
7   2019-10-22 00:00:00       MOTOR  14    420000    
8   2019-03-18 00:00:00  PAPER BRSH  13    520000    
9   2019-07-17 00:00:00        불화카리  23   1909000    
10  2019-07-23 00:00:00         마크펜  33     99000    
11  2019-03-20 00:00:00         NUT  20    300000    
12  2019-01-27 00:00:00         윤활유  30  60000000    
13  2019-07-11 00:00:00         소모품  50    110000    
14  2019-05-16 00:00:00        BITE  14   1204000

In [40]:
# 6

data1 = pd.read_excel('.\\sampleFile\\학생_만족도_조사_실습.xlsx')
data1

연번   학년  소속  분반 1. 튜터링 활동을 위한 자료준비 및 선행학습은 적절하였다.  \
0   1.0  4.0   7 NaN                                 5   
1   2.0  4.0   4 NaN                                 3   
2   3.0  4.0   5 NaN                                 3   
3   4.0  3.0   1 NaN                                 5   
4   5.0  3.0  12 NaN                                 4   
..  ...  ...  ..  ..                               ...   
73  NaN  NaN  11 NaN                                 0   
74  NaN  NaN  12 NaN                                 0   
75  NaN  NaN  13 NaN                                 0   
76  NaN  NaN  14 NaN                                 0   
77  NaN  NaN  15 NaN                                 0   

   2. 튜티의 학습 수준 및 특성을 파악하였다. 3. 활동 중 튜티와의 상호작용을 유도하였다.  \
0                          5                         5   
1                          4                         4   
2                          4                         4   
3                          5                         5   
4                          4                         5   
..                       ...                       ...   
73                         0                         3   
74                         0                         9   
75                         0                         3   
76                         0                         3   
77                         3                         7   

   4. 튜티의 학습 수준 및 특성을 고려하여 활동하였다. 5. 튜터링 활동 시간은 적절하였다.  6. 튜터링 활동 장소는 적절하였다.  \
0                               5                    5                   5.0   
1                               4                    4                   4.0   
2                               5                    4                   4.0   
3                               5                    5                   5.0   
4                               4                    3                   4.0   
..                            ...                  ...                   ...   
73                             21                   34                   NaN   
74                             24                   25                   NaN   
75                             21                   34                   NaN   
76                             25                   30                   NaN   
77                             24                   24                   NaN   

    ...  11. 책임감이 증진되었다.  12. 협동심이 증진되었다.  13. 의사소통능력이 증진되었다.  \
0   ...         5.000000         5.000000            5.000000   
1   ...         4.000000         4.000000            4.000000   
2   ...         4.000000         3.000000            4.000000   
3   ...         5.000000         5.000000            5.000000   
4   ...         4.000000         3.000000            4.000000   
..  ...              ...              ...                 ...   
73  ...         0.051724         0.362069            0.586207   
74  ...         0.155172         0.413793            0.431034   
75  ...         0.051724         0.362069            0.586207   
76  ...         0.051724         0.431034            0.517241   
77  ...         0.120690         0.413793            0.413793   

    14. 티칭스킬이 증진되었다.  15. 학교생활 적응능력이 증진되었다.  16. 효원튜터링 프로그램에 대해 만족한다.  \
0                5.0                    5.0                        만족   
1                4.0                    4.0                        만족   
2                5.0                    4.0                        만족   
3                5.0                    5.0                        만족   
4                5.0                    5.0                        만족   
..               ...                    ...                       ...   
73               NaN                    NaN                       NaN   
74               NaN                    NaN                       NaN   
75               NaN                    NaN                       NaN   
76               NaN                    NaN                       NaN   
77               NaN                    NaN                       

In [41]:
# 7

data2 = pd.DataFrame(data1, columns=['팀활동좋았던점', '운영상 좋았던점'])
data2

팀활동좋았던점                                   운영상 좋았던점
0       의사소통 능력, 리더쉽 능력이 승진되었다.                   보고서를 통해 피드백을 받을 수 있어 좋았다
1   다른과에서 복수전공을 하고오신 튜티를 만나 좋았다  주간 보고서를 제풀해야해서 주당 1회 활동이 의무적으로 이루어 진 것 같다
2                     무난하게 잘 완료                    전공 과목을 대상으로 한다는 점에서 도움됨
3                      질의응답이 활발                              설명을 잘해주셔서 좋았다
4                           NaN                         자율적인 튜터링 활동이어서 좋았다
..                          ...                                        ...
73                          NaN                                        NaN
74                          NaN                                        NaN
75                          NaN                                        NaN
76                          NaN                                        NaN
77                          NaN                                        NaN

[78 rows x 2 columns]